export const CREATE_CATEGORY = "[ERP] CATEGORY/CREATE";
export const READ_CATEGORIES = "[ERP] CATEGORIES/READ";
export const UPDATE_CATEGORY = "[ERP] CATEGORY/UPDATE";
export const DELETE_CATEGORY = "[ERP] CATEGORY/DELETE";
