export const CREATE_CATEGORY_REQUEST = "[ERP] CATEGORY/CREATE-CATEGORY-REQUEST";
export const READ_CATEGORIES_REQUEST = "[ERP] CATEGORIES/READ-CATEGORIES-REQUEST";
export const UPDATE_CATEGORY_REQUEST = "[ERP] CATEGORY/UPDATE-CATEGORY-REQUEST";
export const DELETE_CATEGORY_REQUEST = "[ERP] CATEGORY/DELETE-CATEGORY-REQUEST";

export const CREATE_CATEGORY_SUCCESS = "[ERP] CATEGORY/CREATE-CATEGORY-SUCCESS";
export const READ_CATEGORIES_SUCCESS = "[ERP] CATEGORIES/READ-CATEGORIES-SUCCESS";
export const UPDATE_CATEGORY_SUCCESS = "[ERP] CATEGORY/UPDATE-CATEGORY-SUCCESS";
export const DELETE_CATEGORY_SUCCESS = "[ERP] CATEGORY/DELETE-CATEGORY-SUCCESS";
