export const CREATE_PRODUCT = "[ERP] PRODUCT/CREATE";
export const READ_PRODUCTS = "[ERP] PRODUCTS/READ";
export const UPDATE_PRODUCT = "[ERP] PRODUCT/UPDATE";
export const DELETE_PRODUCT = "[ERP] PRODUCT/DELETE";
