export const CREATE_PRODUCT_REQUEST = "[ERP] PRODUCT/CREATE-PRODUCT-REQUEST";
export const READ_PRODUCTS_REQUEST = "[ERP] PRODUCTS/READ-PRODUCTS-REQUEST";
export const UPDATE_PRODUCT_REQUEST = "[ERP] PRODUCT/UPDATE-PRODUCT-REQUEST";
export const DELETE_PRODUCT_REQUEST = "[ERP] PRODUCT/DELETE-PRODUCT-REQUEST";

export const CREATE_PRODUCT_SUCCESS = "[ERP] PRODUCT/CREATE-PRODUCT-SUCCESS";
export const READ_PRODUCTS_SUCCESS = "[ERP] PRODUCTS/READ-PRODUCTS-SUCCESS";
export const UPDATE_PRODUCT_SUCCESS = "[ERP] PRODUCT/UPDATE-PRODUCT-SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "[ERP] PRODUCT/DELETE-PRODUCT-SUCCESS";
