export const CREATE_STOCK_REQUEST = "[ERP] STOCK/CREATE-STOCK-REQUEST";
export const READ_STOCKS_REQUEST = "[ERP] STOCKS/READ-STOCKS-REQUEST";
export const UPDATE_STOCK_REQUEST = "[ERP] STOCK/UPDATE-STOCK-REQUEST";
export const DELETE_STOCK_REQUEST = "[ERP] STOCK/DELETE-STOCK-REQUEST";

export const CREATE_STOCK_SUCCESS = "[ERP] STOCK/CREATE-STOCK-SUCCESS";
export const READ_STOCKS_SUCCESS = "[ERP] STOCKS/READ-STOCKS-SUCCESS";
export const UPDATE_STOCK_SUCCESS = "[ERP] STOCK/UPDATE-STOCK-SUCCESS";
export const DELETE_STOCK_SUCCESS = "[ERP] STOCK/DELETE-STOCK-SUCCESS";
