export const ERP_INIT = '[ERP] INIT';
export const GET_PRODUCTS = '[ERP] PRODUCTS/GET';
export const CREATE_PRODUCT = '[ERP] PRODUCT/CREATE';
export const UPDATE_PRODUCT = '[ERP] PRODUCT/UPDATE';
export const REMOVE_PRODUCT = '[ERP] PRODUCT/REMOVE';

export const GET_CATEGORIES = '[ERP] CATEGORIES/GET';
export const CREATE_CATEGORY = '[ERP] CATEGORY/CREATE';
export const UPDATE_CATEGORY = '[ERP] CATEGORY/UPDATE';
export const REMOVE_CATEGORY = '[ERP] CATEGORY/REMOVE';

export const GET_STOCKS = '[ERP] STOCKS/GET';
export const CREATE_STOCK = '[ERP] STOCK/CREATE';
export const UPDATE_STOCK = '[ERP] STOCK/UPDATE';
export const REMOVE_STOCK = '[ERP]'
