export const PRODUCTS_SET = '[ERP] PRODUCTS/SET';
export const PRODUCT_CREATED = '[ERP] PRODUCT/CREATED';
export const PRODUCT_UPDATED = '[ERP] PRODUCT/UPDATED';
export const PRODUCT_REMOVED = '[ERP] PRODUCT/REMOVED';

export const CATEGORIES_SET = '[ERP] CATEGORIES/SET';
export const CATEGORY_CREATED = '[ERP] CATEGORY/CREATED';
export const CATEGORY_UPDATED = '[ERP] CATEGORY/UPDATED';
export const CATEGORY_REMOVED = '[ERP] CATEGORY/REMOVED';

export const STOCKS_SET = '[ERP] STOCKS/SET';
export const STOCK_CREATED = '[ERP] STOCK/CREATED';
export const STOCK_UPDATED = '[ERP] STOCK/UPDATED';
export const STOCK_REMOVED = '[ERP] STOCK/REMOVED';
